### ISSUE TITLE
Some images become all 0 or NaN after sparse deconvolution

### ISSUE THREAD

**Issue by ptbrown1729** [WeisongZhao/Sparse-SIM#1] opened 2021-03-22 21:31 UTC
Hello, thanks for making this available! I've been trying out the Sparse SIM release 1.0.3 with Matlab 2017b on a machine running Windows 10 enterprise. Some images that I apply it on produce very nice results, but for some the output is all zeros in the tiff file, and the variable SHdeblurCPU from the .mat file is all NaN's. I assume that the input image file I supply is not meeting the assumptions of the program in these cases, but I don't see any errors being thrown. I am hoping you have some advice on how to figure out what goes wrong with these images.

**Comment by WeisongZhao** [comment] 2021-03-23 01:42
Hi, the problem you mentioned is caused by the small bug of the `deconvolution feature` in the released version you used. 
We will release a `bug fixed` new version (including `.exe` and `source code`) once the manuscript is accepted.
You can use the option `No deconvolution` in the current version.

**Comment by ptbrown1729** [comment] 2021-03-23 15:57
@WeisongZhao thanks!

**Comment by WeisongZhao** [comment] 2021-07-18 15:20
Hi ptbrown1729,
I'm closing this issue, and gladly leaving a notification to you in case you haven't noticed that the `source code` has beed released.
Now, you can use the `source code` directly to process your data. 
Have fun!
Feedback, questions, bug reports and patches are welcome and encouraged!

**Closed as completed** 2021-07-18 15:20 UTC
Labels: bug
